name: "Continuous Deployment"

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Install dependencies
        run: |
          cd hello-world
          npm install
          cd ..
          zip -r hello-world-terraform-aws.zip hello-world/ -x "hello-world/tests/*"
      - name: Deploy Lambda function to AWS
        run: |
          aws lambda update-function-code --function-name HelloWorld --zip-file fileb://hello-world-terraform-aws.zip
          aws lambda update-function-code --function-name ByeWorld --zip-file fileb://hello-world-terraform-aws.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-southeast-1"
