name: "Continuous Integration"

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Install dependencies
        run: |
          cd hello-world
          npm install
